### ISSUE TITLE
[Question] about `Moon Day Speed Multiplier Patcher` and `Moon Scrap Limits Patch`

### ISSUE THREAD

**Issue by CoolLKKPS** [WhiteSpike/Moon-Day-Speed-Multiplier-Patcher#1]
about `Moon Day Speed Multiplier Patcher`
does this necessary if i install `LethalCompanyVariables`? bc i didn't trigger this glitch

about `Moon Scrap Limits Patch`
ok so when i set the total value cap in `levelloader`, does `CentralConfig` or `LethalCompanyVariables` can recognize the value and correctly multiplier them?

**Comment by CoolLKKPS** [comment]
@WhiteSpike if u can answer those question rq i will be appreciated

**Comment by WhiteSpike** [comment]
Both the mods are only relevant if you have some way to alter the relevant items to them.
If you can alter the time speed multiplier of a moon and/or some moon creator inserted a multiplier different than 1.0, you should use ``Moon Day Speed Multiplier Patcher``
If you can alter the minimum and maximum total scrap values of a moon (the same way as the minimum and maximum amount of scrap items it can spawn on that moon) and you want them to be used in the generation of scrap (vanilla does not take account the limits of total scrap value stored on each moon), you should use ``Moon Scrap Limits Patch``.

> ok so when i set the total value cap in levelloader, does CentralConfig or LethalCompanyVariables can recognize the value and correctly multiplier them?

I don't know when they apply the multiplier but if they apply during scrap generation then yes, they should be able to work correctly. If they do so after all the scrap has generated (in other words ignoring the scrap generation entirely and just waiting for any scrap to spawn to increase its value), then no.

**Comment by CoolLKKPS** [comment]
thx, i will do some test with LethalCompanyVariables, will let u know if ur mod compatible with that

**Comment by CoolLKKPS** [comment]
ok, at least i know `Moon Scrap Limits Patch` did not work properly
1. with `LethalCompanyVariables`, this mod does nothing, total scrap value always `842`
2. without `LethalCompanyVariables` or anything related (except `levelloader`), sometime this mod works, but sometime is not, i set the total scrap value limit to 300-700, and also exactly the same seed, i got 2 results, `695`x1 and `839`x2

maybe i still miss something, hang on

**Comment by WhiteSpike** [comment]
It will always stop at whatever limit it reaches first.
If it spawned enough scrap items or it has reached the selected total scrap value for that round.
This obviously if the vanilla mechanic is being executed as that is what it was patched. If anything changes the scrap generation entirely, it will not work.
I will take a look when I have the time, it's like 3 AM.

Edit: I don't remember this exactly but same scrap days are not restricted the same way as normal scrap generation.

**Comment by CoolLKKPS** [comment]
ok i will test this rq, so i know ur mod conflict with LethalCompanyVariables and FacilityMeltdown (for my modpack this mod is necessary), also maybe conflict with WeatherRegistry and MeteoMultiplier even im not use those
to multiplier the value, anyway now ur mod works properly, but i did need to test and try reproduce if im not install this mod

**Comment by WhiteSpike** [comment]
Also map objects such as the apparatus are not considered in the scrap generation restrictions.

**Comment by CoolLKKPS** [comment]
i use this seed `94315519` and play with `March` (1% vanilla meteor shower, just happen today, my favorite seed now)

**Without FacilityMeltdown**
Vanilla is `863`
Moon Scrap Limits Patch is `675`
LethalCompanyVariables is `869`
Both install will cause issue, same seed but diff value

*sorry for the delay bc the network issue*

**Comment by CoolLKKPS** [comment]
> Vanilla is 863

its not really vanilla btw bc i installed some custom scraps, but should be fine i think

**Comment by WhiteSpike** [comment]
Already tested with 80 scrap item spawns and 400 total scrap value in Experimentation and it always respects the boundaries set through total scrap value.

The only argument I can see here is that the last scrap item that spawns can (and most likely will) surpass over the total scrap value limit, thus it won't be exactly the same value as you set in the maximum.

"Then you can just decrease the value of the last one to be exact!"
So you want the last one to have the value of one credit worth? Because that's likely what's going to happen if I do that and I doubt people will like seeing a scrap worth of one credit. It might aswell just not spawned at all.

**Comment by CoolLKKPS** [comment]
if changed the last spawn scrap value, pretty sure that's not what i like to see, i more like to see the mod respect the vanilla behavior, but limit the total value and that value not go too far from what i set it
in my case, sometime the total scrap value even below to 583, with LethalCompanyVariables (i didn't change any setting on that mod), that's what we need to investigate

**Comment by CoolLKKPS** [comment]
i will re-open this once i have free time to check (hope that won't take long)
